Feature swc 63 crear endpoint para recibir informacion de una partida especifica
HoodedHackers/Backend pull request #12
Opened 2024-09-24 03:22 UTC by MatiasScantamburlo

Listar una partida especifica por id **terminado** ¡Espero su revisión! 💯

2024-09-24 14:58 UTC, KaiserOfNone requested changes

2024-09-24 14:58 UTC, KaiserOfNone commented on main.py
> +    lobby = repo.get(id)
No, nunca mandes lo que tenemos en la DB pelado al cliente. En la DB estan los identificadoes de cada jugador que son secretos.
Arma una class `GameStateOutput` o algo asi que siga lo que dice en el ticket.

2024-09-24 14:58 UTC, KaiserOfNone commented on repositories/game.py
> +    def get_available(self, count: int = 10) -> List[Game]:
Porque cambiaste esto? 
1. No va al ticket.
2. El None te permite no pasar el argumento y que te de todos. Este cambio elimina ese comportamiento.

2024-09-24 14:58 UTC, KaiserOfNone commented on tests/test_get_game.py
> +def test_get_game():
Agrega jugadores a la partida en el test.

2024-09-27 12:01 UTC, MatiasScantamburlo commented on main.py
> +    lobby = repo.get(id)
Sisi, tenés razón ¡Gracias Andi!

2024-09-27 12:11 UTC, MatiasScantamburlo commented on repositories/game.py
> +    def get_available(self, count: int = 10) -> List[Game]:
Mala mía, se me filtro en el commit. Obviamente no va

No te preocupes entiendo el funcionamiento, solo que el editor me lo marcaba como error de tipado y lo cambie para que no me dolieran los ojos jajaja.

2024-09-27 12:35 UTC, KaiserOfNone commented on repositories/game.py
> +    def get_available(self, count: int = 10) -> List[Game]:
Podes cambiarlo por un `Optional[int]` si apacigua al linter.

2024-09-27 13:55 UTC, MatiasScantamburlo commented on repositories/game.py
> +    def get_available(self, count: int = 10) -> List[Game]:
Me encantó

2024-09-27 18:31 UTC, KaiserOfNone commented on repositories/game.py
> +    def get_available(self, count: int = 10) -> List[Game]:
Si es onda lo mismo.

2024-09-27 18:40 UTC, KaiserOfNone approved these changes
Corre `make format` y podes mergearlo.

2024-09-27 18:40 UTC, KaiserOfNone commented on main.py
> +class GameStateOutput(BaseModel):
Veo que no hay data sobre los jugadores. No importa por ahora, se puede hacer despues. Escribi un ticket de "agregar informacion de tarjetas" o algo asi para ponerlo despues. (dado que no tenemos mucho de tarjetas aun)

Este comment no es bloqueante, es informativo.

2024-09-28 16:38 UTC, merged