Swc 78 arreglar endpoint de salir de partida
HoodedHackers/Backend pull request #34
Opened 2024-10-08 00:52 UTC by LourdesMamani00

Buenas, a este endpoint le falta solo los ws pero tengo algo en pseudocodigo.
Agregue nuevos tests y nuevas funcionalidaes:
Si el jugador esta en partida pueda salir sin ningun problema.
Si es el host y aun no empezo la partida entonces se elimina la sala.
Agregue comentarios respecto a los tests y los disntintos casos para los distintos escenarios.
Este pr contempla la refactorizacion, y una funcionalidad del sprint 2 pero no ws, aun asi creo que es bueno mergearlo a la rama develop.

2024-10-08 12:43 UTC, KaiserOfNone requested changes
Rojo por lo del identifier. No se pasa.

2024-10-08 12:43 UTC, KaiserOfNone commented on main.py
> +        id=lobby_query.id, started=lobby_query.started, players=list_players
Esto es mas de integracion, pero cuando se llama a salir, el usuario que quiere salir es el que llama este endpoint, para que le hace falta saber que jugadores quedan en la lista?

2024-10-08 12:43 UTC, KaiserOfNone commented on main.py
> +        PlayersOfGame(identifier=UUID(str(player.identifier)), name=player.name)
no no no no, no des el identifier para otros jugadores!!!! acordate que es secreto

2024-10-08 12:43 UTC, KaiserOfNone commented on model/game.py
> +from sqlalchemy.ext.orderinglist import ordering_list
para que este import?

2024-10-08 12:43 UTC, KaiserOfNone commented on services/connection_manager.py
> +                await connection.send_text(message)  # cambiar esto muy posiblemente
Este tipo de cosas van en un ticket, no el los comentarios.

2024-10-08 12:43 UTC, KaiserOfNone commented on tests/test_exit_game.py
> +from main import game_repo
estas haciendo `from main ...` varias veces.

2024-10-09 00:12 UTC, LourdesMamani00 commented on services/connection_manager.py
> +                await connection.send_text(message)  # cambiar esto muy posiblemente
a eso era un comentario para mi misma

2024-10-09 00:19 UTC, LourdesMamani00 commented on tests/test_exit_game.py
> +from main import game_repo
jajaja cai en la misma trampa jajajaj

2024-10-09 00:20 UTC, LourdesMamani00 commented on model/game.py
> +from sqlalchemy.ext.orderinglist import ordering_list
creo que habia mergeado mal eso

2024-10-09 00:20 UTC, LourdesMamani00 commented on model/game.py
> +from sqlalchemy.ext.orderinglist import ordering_list
ahora lo saco

2024-10-09 00:21 UTC, LourdesMamani00 commented on main.py
> +        PlayersOfGame(identifier=UUID(str(player.identifier)), name=player.name)
okas, es un secreto, igual ahi hasta ahora no me dijeron e  front que debia devolver o retornar asi que lo deje asi

2024-10-09 00:23 UTC, LourdesMamani00 commented on main.py
> +        id=lobby_query.id, started=lobby_query.started, players=list_players
supuse que debia actualizarles a los de front la lista de jugadores, todavia no lo charle con Ema

2024-10-09 00:23 UTC, LourdesMamani00 commented on main.py
> +        id=lobby_query.id, started=lobby_query.started, players=list_players
aun queda hacer integracion

2024-10-13 18:02 UTC, KaiserOfNone requested changes
Tus tests no pasan, el codigo no es valido.

2024-10-13 18:02 UTC, KaiserOfNone commented on main.py
> +import services.connection_manager
No, ya estamos importando Managers de services. Linea 19.

2024-10-13 18:02 UTC, KaiserOfNone commented on main.py
> +    return Managers.get_manager(ManagerTypes.JOIN_LEAVE)
Esta mal, Managers ya esta importado, no estas usando request para nada, el tipo del manager esta hardcodeado cuando manager ya tiene la funcion get manager. En general cuando tenes una funcion de una sola linea es un indicador de que esa funcion no hace falta.

2024-10-13 18:02 UTC, KaiserOfNone commented on main.py
> +    id_player: UUID  # NO LE ENVIO ESTO id int
Entonces no lo envies.

2024-10-13 18:02 UTC, KaiserOfNone commented on main.py
> -
Estos cmabios no son necesarios, porque los hiciste?

2024-10-13 18:02 UTC, KaiserOfNone commented on main.py
> +    id: int,
usa lobby_id para evitar ambiguedad

2024-10-13 18:02 UTC, KaiserOfNone commented on main.py
> +    #puedo usar manager.get_manager
Entonces usalo

2024-10-13 18:02 UTC, KaiserOfNone commented on main.py
> +    player_exit = repo_player.get(ident.id_play)  # ver
Porque no usas el identifier? Este endpoint necesita ser autenticado. Asi yo puedo mandar pedidos de salir como cualquier jugador sin restricciones.

2024-10-13 18:02 UTC, KaiserOfNone commented on main.py
> +    # si el host se quiere ir y el juego no empezo, se borra el lobby
Saca todos estos comentarios che.

2024-10-13 18:02 UTC, KaiserOfNone commented on tests/test_unlock_game_not_started.py
> -from unittest import skip
git rm <archivo>

2024-10-13 18:02 UTC, KaiserOfNone commented on main.py
> +    repo.save(lobby_query)
Aca hay un bug. estas borrando y re-agregando al salir del if.

2024-10-13 18:02 UTC, KaiserOfNone commented on main.py
> +        await leave_manager.disconnect(websocket, id, player_exit.id)
Donde definiste websocket? Esto no existe. Dijiste que hibas a cambiar la api, cambiala entonces.

2024-10-17 12:52 UTC, closed without merging