Swc 130 implementar web socket para mostrar la carta de movimiento
HoodedHackers/Backend pull request #40
Opened 2024-10-15 11:21 UTC by MatiasScantamburlo

¡Chicos acá dejo una PR! Espero sus comentarios :100:

2024-10-17 23:06 UTC, KaiserOfNone requested changes

2024-10-17 23:06 UTC, KaiserOfNone commented on main.py
> +    player = player_repo.get(player_id)
player lo estas obteniendo en la linea 556 abajo.

2024-10-17 23:06 UTC, KaiserOfNone commented on main.py
> +            game.add_player(player)
El ws no es responsable de agregar jugadores, para eso esta el endpoint.

2024-10-17 23:06 UTC, KaiserOfNone commented on main.py
> +    Se espera: {card_id: 'valor', player_identifier: 'valor'}
Pone tipos, no solo valor, eso no me dice nada.

2024-10-17 23:06 UTC, KaiserOfNone commented on main.py
> +            hand = game.player_info[current_player.id].hand_mov
Esto es horrible. Usa un metodo en game para sacar esta data, player_info es un detalle de implementacion.

2024-10-17 23:06 UTC, KaiserOfNone commented on main.py
> +        raise HTTPException(status_code=404, detail="Player not found")
Esto no hace falta. El primer mensaje te debe dar el identifier de todas formas, podes extraer el id de ahi,

2024-10-17 23:06 UTC, KaiserOfNone commented on model/__init__.py
> +from .game import Game, PlayerInfo
No exportes PlayerInfo, no lo exporte a proposito.

2024-10-17 23:06 UTC, KaiserOfNone commented on tests/test_select_card.py
> +            id=101010,
No hardcodees la ID, genera tests que se pueden romper facilmente. Cuando haces save los campos con valores por defecto se llenan automaticamente.

2024-10-17 23:06 UTC, KaiserOfNone commented on tests/test_select_card.py
> +                )
No hagas esto, sobreescribi los campos que necesitas, o mejor todavia, agrega metodos para trabajar la data que necesitas.

2024-10-17 23:06 UTC, KaiserOfNone commented on tests/test_select_card.py
> +                ) as websocket1:
Pone todas las conecciones al ws al principio, en otros tests lo estamos haciendo asi.

2024-10-17 23:09 UTC, KaiserOfNone commented on main.py
> +    Se espera: {card_id: 'valor', player_identifier: 'valor'}
Agrega un campo al json que se retorna que sea `"action": "play"`, lo necesitamos para cuando tengamos el `"action": "undo"` para saber cuando mostrar y esconder cartas en el front.

2024-10-18 12:55 UTC, seedLou commented on main.py
> +            game.add_player(player)
El ws tambien puede agregar al jugador (que era la unica responsabilidad del endpoint ademas de las verificaciones que el ws por cierto tambien hace)  funciono bien en la integracion, por eso dijimos ¿para que queremos al endpoint si lo unico que hace tambien puede hacerlo el ws?

2024-10-18 13:01 UTC, seedLou commented on main.py
> +    Se espera: {card_id: 'valor', player_identifier: 'valor'}
Todas las cartas de movimiento estan ocultas hasta que se juegan. Si los demas jugadores reciben el json con el player_id de otro jugador entonces la carta se muestra hasta que se descarte (ya no existe in deck) o se reviertan los movimientos parciales (aca el action seria "undo" nuevamente)

2024-10-18 13:05 UTC, seedLou commented on main.py
> +            hand = game.player_info[current_player.id].hand_mov
Me sirve porque tambien use descaradamente player_info 
Ahora creo un metodo para acceder a esa data sin romper toda la abstraccion ahhhhh curioso

2024-10-19 17:55 UTC, MatiasScantamburlo commented on main.py
> +    player = player_repo.get(player_id)
La primera vez tiene sentido para corroborar que exista el player antes de agregar su conexion al diccionario. Lo que podría estar en duda es si necesitamos que se pase el identifier, ya que seguramente será el del jugador previamente conectado, eso se podría mejorar.

Sin embargo corroborar que el identifier pasado existe no está mal.

2024-10-19 17:57 UTC, MatiasScantamburlo commented on main.py
> +    Se espera: {card_id: 'valor', player_identifier: 'valor'}
Voy a mejorar los comentarios remplazando 'valor' por el tipo que se espera. Por ejemplo:

{card_id: 'int', player_identifier: 'str'}

2024-10-19 18:03 UTC, MatiasScantamburlo commented on main.py
> +            hand = game.player_info[current_player.id].hand_mov
Banco, mejoremos esto

2024-10-19 18:14 UTC, MatiasScantamburlo commented on main.py
> +        raise HTTPException(status_code=404, detail="Player not found")
¿Porqué decís que no hace falta? ¿Como corroboro que no se conecten con un game_id inexistente?

2024-10-19 18:18 UTC, MatiasScantamburlo commented on model/__init__.py
> +from .game import Game, PlayerInfo
Lo necesito para crear instancias de figura en la mano del jugador. Puedo crear un método que abstraiga esto si no querés importar PlayerInfo

2024-10-19 18:45 UTC, MatiasScantamburlo commented on tests/test_select_card.py
> +            id=101010,
¡Listo!

2024-10-19 18:46 UTC, MatiasScantamburlo commented on tests/test_select_card.py
> +                )
¡Hecho!

2024-10-19 18:47 UTC, MatiasScantamburlo commented on tests/test_select_card.py
> +                ) as websocket1:
Mi vida por la horda

2024-10-19 18:49 UTC, MatiasScantamburlo commented on model/__init__.py
> +from .game import Game, PlayerInfo
Ahí lo dejé mejor y ya no hay necesidad de importarlo :heart_hands:

2024-10-19 20:13 UTC, merged