Swc 39 crear carta movimiento fix
HoodedHackers/Backend pull request #70
Opened 2024-11-02 21:45 UTC by seedLou

Bueno los test por obvios motivos no andannn 
destruyan este pr plis

2024-11-02 21:55 UTC, MatiasScantamburlo commented on services/connection_manager.py
> +        for lobby in self.lobbies[lobby_id]:
El nombre podría ser **send_single_player** y la variable con la que se realiza el ciclo **player** :+1:

2024-11-02 22:08 UTC, MatiasScantamburlo commented on main.py
> +            "cardMov": handMov
Cuando enviaba mensajes por el manejador CARDS_MOV usaba una estructura del tipo
```
{
              "action": "select",
              "player_id": --,
              "card_id": --,
              "index": --,
              "len": --,
}, 
```
Para este caso no tiene sentido usar esto pero desde el front filtran las distintos tipos de mensajes enviados por este con este manejador por el campo **action**. Un ejemplo pavo podría ser usar algo como:
```

{
    "action": add
    "cardMov": handMov
}
```

2024-11-02 22:17 UTC, KaiserOfNone requested changes

2024-11-02 22:17 UTC, KaiserOfNone commented on main.py
> +        handMov = deal_card_mov(selec_game, player, game_repo)
`handMov` (no sigue el standard de nombres) esta siendo sobreescrito por cada jugador. Solo va a tener data del ultimo jugador en la lista. Creo que deberias apendar un dict o algo asi

2024-11-02 22:17 UTC, KaiserOfNone commented on main.py
> +            "cardMov": handMov
ok, ahi veo lo que quieres hacer, asegurate que las cartas que envias sean las del jugador que queres, antes fuiste por todos los jugadores

2024-11-02 22:17 UTC, KaiserOfNone commented on main.py
> +async def card_mov(
```suggestion
async def notify_movement_card_changes(
```
Asi es mas descriptivo

2024-11-02 22:17 UTC, KaiserOfNone commented on main.py
> +@app.websocket("/ws/lobby/{game_id}/cardMovs")
```suggestion
@app.websocket("/ws/lobby/{game_id}/movement_cards")
```

2024-11-02 22:17 UTC, KaiserOfNone commented on main.py
> +            "card_mov": "List[card.id]"
```suggestion
            "card_mov": [card_id]
```

2024-11-02 22:17 UTC, KaiserOfNone commented on main.py
> +            "len": len(hand) | len(mov_parcial),
creo que estas sobrecargando que hace este campo

2024-11-02 22:17 UTC, KaiserOfNone commented on main.py
> +    Retorta broadcast de tipo:
mandar dos tipos distintos de mensajes le complica al front trabajarlo, unifica la forma onda que sea identico en ambos casos.

2024-11-02 22:17 UTC, KaiserOfNone commented on main.py
> +@app.post("/api/lobby/{game_id}/movs")
```suggestion
@app.post("/api/lobby/{game_id}/use_movement_card")
```

2024-11-02 22:17 UTC, KaiserOfNone commented on main.py
> +async def select_card_mov(
```suggestion
async def select_movement_card(
```

2024-11-02 22:17 UTC, KaiserOfNone commented on main.py
> +    movs_game = game.all_movs
che tener nombres largos no hace el codigo mas lento, movs_game no es muy descriptivo

2024-11-02 22:17 UTC, KaiserOfNone commented on main.py
>      conjunto = set()
Cambia este nombre, conjunto no me da nada de idea de que es. de hecho no hace falta que sea un conjunto, podes tener dos cartas del mismo tipo, si es un conjunto eso no puede pasar...

2024-11-02 22:21 UTC, seedLou commented on main.py
> +        handMov = deal_card_mov(selec_game, player, game_repo)
AY ES VERDAD. Gracias pa

2024-11-02 23:13 UTC, seedLou commented on main.py
> +            "len": len(hand) | len(mov_parcial),
Te referis al "len"?

2024-11-02 23:13 UTC, seedLou commented on main.py
> +    Retorta broadcast de tipo:
bueno dale

2024-11-02 23:19 UTC, seedLou commented on main.py
> +    movs_game = game.all_movs
SJDHSJDHSJDS srry

2024-11-02 23:21 UTC, seedLou commented on main.py
>      conjunto = set()
si hace falta que sea un conjunto, porque tenes id por cada carta, tener dos cartas de id 34 no es para nada valido 
Tener dos cartas iguales si pero sus ids son diferentes (1 y 8 por ejemplo referieren a la misma carta pero 1 no es igual a 8)

2024-11-02 23:27 UTC, MatiasScantamburlo commented on main.py
> +@app.websocket("/ws/lobby/{game_id}/cardMovs")
🐍

2024-11-02 23:30 UTC, MatiasScantamburlo commented
Mi aporte es que creo que no andan los test

2024-11-07 14:08 UTC, KaiserOfNone reviewed
Che ojo cuando usas random, en los tests mockea random por un `random.Random(42)` o algo asi, esto fija la seed asi las tests siempre dan lo mismo.

2024-11-07 14:08 UTC, KaiserOfNone commented on main.py
> +#     return mov_hand
Borra esto :)

2024-11-07 14:08 UTC, KaiserOfNone commented on main.py
> +            },
Tip: Para evitar accidentes de campos que falten o typos pone una funcion que te genere este dict. Onda como `board_status_message`

2024-11-07 14:08 UTC, KaiserOfNone commented on model/game.py
> +        self.player_info[id] = PlayerInfo(
No teniamos un `PlayerInfo.clone()`? Si no ignora este comment.

2024-11-07 14:08 UTC, KaiserOfNone commented on model/game.py
> +        movs_in_self = self.all_movs
Para que esto?

2024-11-07 14:08 UTC, KaiserOfNone commented on tests/test_advance_turn.py
> +                    # no anda el test
Sigue roto?

2024-11-07 18:03 UTC, closed without merging