Feature swc 67 añadir notificaciones por web socket para conexión y desconexión en lobbies
HoodedHackers/Backend pull request #9
Opened 2024-09-23 17:07 UTC by MatiasScantamburlo

Notificar a jugadores  de un mismo lobby la conexión y desconexión de otro jugador **terminado** ¡Espero su revisión! 💯

2024-09-24 14:58 UTC, KaiserOfNone commented
No hagas el merge contra main, es contra develop

2024-09-24 15:07 UTC, KaiserOfNone requested changes

2024-09-24 15:07 UTC, KaiserOfNone commented on main.py
> +async def websocket_endpoint(websocket: WebSocket, lobby_id: int):
Este nombre es demasiado generico. No me dice nada.

2024-09-24 15:07 UTC, KaiserOfNone commented on main.py
> +    await manejador.conectar(websocket, lobby_id)
1. Splanglish.
2. El `LobbyManager` o algo asi (no uses nombres genericos) deberia ser una dependencia onda como estamos haciendo los repositorios.

2024-09-24 15:07 UTC, KaiserOfNone commented on main.py
> +    await manejador.broadcast(f"Un nuevo jugador ha ingresado al lobby {lobby_id}.", lobby_id)
Porque mandas strings pelados. Acordamos que ibamos a mandar json

2024-09-24 15:07 UTC, KaiserOfNone commented on main.py
> +            await websocket.receive_text()
Que estas esperando recibir. Esto no hace nada.

2024-09-24 15:07 UTC, KaiserOfNone commented on main.py
> +        await manejador.broadcast(f"Un jugador ha abandonado el lobby {lobby_id}.", lobby_id)
Idem arriba. No mandes strings pelados.

2024-09-24 15:07 UTC, KaiserOfNone commented on services/connection_manager.py
> +class ManejadorConexionesLobby:
Init? Conectar? Broadcast? Spanglish.

2024-09-24 15:07 UTC, KaiserOfNone commented on services/connection_manager.py
> +            if len(self.lobbies[lobby_id]) == 0:
No. El responsable de verificar si se debe borrar la conexion es el que llama
1. La funcion esta falla silenciosamente si le pedis borrar algo que no tiene.
2. Que pasa si queres borrar una partida aunque haya conexiones?

2024-09-24 15:07 UTC, KaiserOfNone commented on tests/test_actualizar_lobby.py
> +from fastapi.testclient import TestClient
Igual que en el otro archivo. Estandariza a ingles. El resto de la base de codigo esta en ingles.

2024-09-27 15:38 UTC, MatiasScantamburlo commented on main.py
> +            await websocket.receive_text()
No espero nada,  solamente lo dejo para mantener la conexión abierta. Así entendí que funcionaba, sino hace falta y sin eso la conexión no se cierra, puedo sacarlo.

2024-09-27 18:00 UTC, MatiasScantamburlo commented on main.py
> +            await websocket.receive_text()
El comentario está desactualizado. En aquel momento creía que `receive_text` era necesario para mantener la conexión de ws abierta. Ahora esa linea está porque se espera recibir las notificaciones de entrada y salida de los demás jugadores a la sala

2024-09-27 18:41 UTC, KaiserOfNone commented on main.py
> +            await websocket.receive_text()
Pero estas leyendo y descartando. Esto literal no hace nada.

2024-09-27 19:02 UTC, MatiasScantamburlo commented on main.py
> +            await websocket.receive_text()
Ahí entendí Andy. Pensaba que había que capturar de alguna forma los mensajes, entre las conexiones, para que pudieran llegar al front, en mi cabeza esto lo hacía el `receive_text`. Ahí vi que de eso se encarga el `send_text` (o mejor dicho ahora lo hace el `send_json`, cuando suba los cambios). Así que habría que sacar la linea que me citaste :+1:

2024-09-27 19:54 UTC, MatiasScantamburlo commented on main.py
> +            await websocket.receive_text()
Sin embargo el while true debería tener algo que lo ponga al proceso en descanso para que no esté gastando CPU innecesariamente. Creo que en ese sentido es razonable dejar el `receive_text`.

2024-09-30 19:42 UTC, LourdesMamani00 approved these changes

2024-09-30 19:42 UTC, LourdesMamani00 commented on main.py
tal vez debamos crear un archivo aparte para websockets pero creo que por el momeno si funciona en main entonces creo que para la entrega est'a

2024-09-30 19:42 UTC, LourdesMamani00 commented on main.py
parece que hay que actualizar la rama

2024-10-02 13:55 UTC, KaiserOfNone reviewed
`make format` is your friend :)

Mas que nada el tema es el diseño del manager, tipo el manager deberia ser el que se encarga de toda la logica de que se envia y el websocket_handler deberia solo levantar y bajar la conexion

2024-10-02 13:55 UTC, KaiserOfNone commented on main.py
> +    await connection_manager.broadcast(f"Un nuevo jugador se ha unido al lobby {lobby_id}.", lobby_id)
El manager es el que se encarga de que enviar me parece. Cuando lamas connect el mismo manager deberia avisar
Also envia algo como
```json
{ "player_name": "name" }
```

2024-10-02 13:55 UTC, KaiserOfNone commented on main.py
> +        await connection_manager.broadcast(f"Un jugador ha abandonado el lobby {lobby_id}.", lobby_id)
Mismo que el otro comment. Deja que el manager envie eso y manda un json.

2024-10-02 13:57 UTC, KaiserOfNone commented on main.py
> +            await websocket.receive_text()
Para saber que jugador es el que se esta conectando seguaremnte vas a tener que leer el identifier que te lo manden por el ws al inicio de la interaccion.

2024-10-02 14:07 UTC, MatiasScantamburlo commented on main.py
> +    await connection_manager.broadcast(f"Un nuevo jugador se ha unido al lobby {lobby_id}.", lobby_id)
Estás bueno, avisar al front que la conexión ha sido exitosa enviando el nombre del jugador conectado

2024-10-02 14:15 UTC, MatiasScantamburlo commented on main.py
> +        await connection_manager.broadcast(f"Un jugador ha abandonado el lobby {lobby_id}.", lobby_id)
El sistema de broadcast se encarga de enviar un JSON con el siguiente formato: {"message": <mensaje>} a un lobby específico.

Por ejemplo, en caso de una desconexión en el lobby 3, el endpoint correspondiente recibiría el siguiente mensaje:
{"message": "Un jugador ha abandonado el lobby 3"}

2024-10-02 14:22 UTC, MatiasScantamburlo commented on main.py
> +        await connection_manager.broadcast(f"Un jugador ha abandonado el lobby {lobby_id}.", lobby_id)
La razón por la cual no envió el mensaje directamente, a través del método connect o disconnect, es para generalizar la clase y mejorar su reúso en próximos endpoints ws

2024-10-02 19:30 UTC, KaiserOfNone requested changes
El resto se ve bien, solo el comment que te dije y esta para mergear

2024-10-02 19:30 UTC, KaiserOfNone commented on services/connection_manager.py
> +                    await websocket.send_json({"error": "User not found"})
Podes bajar el nivel de indentacion, mas que nada para evitar errores logicos, inverti los checkeos y hace un retorno especifico cuando sale algo mal. Tipo asi cuando alguien manda mal un json le llega un error raro poco descriptivo. Fijate con un test.

2024-10-06 00:13 UTC, LourdesMamani00 approved these changes

2024-10-07 14:14 UTC, LourdesMamani00 approved these changes

2024-10-07 14:14 UTC, LourdesMamani00 commented on services/connection_manager.py
> +        self, websocket: WebSocket, lobby_id: int, player_repo: PlayerRepository
creo que esta bien y como hablamos antes en la llamada supongo que vamos a ir modificando una que otra cosa a medida que avanzamos

2024-10-16 15:18 UTC, closed without merging